require_relative '../ReactNativeModule/node_modules/react-native/scripts/react_native_pods'

node_modules_path = File.expand_path('../ReactNativeModule/node_modules', __dir__)
ENV['REACT_NATIVE_NODE_MODULES_DIR'] = node_modules_path

# Symlink node_modules into Expenso/ so Node can resolve react-native from here
local_node_modules = File.join(__dir__, 'node_modules')
unless File.exist?(local_node_modules)
  File.symlink('../ReactNativeModule/node_modules', local_node_modules)
end

platform :ios, '16.0'
prepare_react_native_project!

target 'Expenso' do
  use_react_native!(
    :path => '../ReactNativeModule/node_modules/react-native',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  pod 'RNReanimated', :path => '../ReactNativeModule/node_modules/react-native-reanimated'
  pod 'RNGestureHandler', :path => '../ReactNativeModule/node_modules/react-native-gesture-handler'
  pod 'RNSVG', :path => '../ReactNativeModule/node_modules/react-native-svg'

  post_install do |installer|
    react_native_post_install(
      installer,
      '../ReactNativeModule/node_modules/react-native',
      :mac_catalyst_enabled => false
    )

    # Workaround for fmt consteval errors with Xcode 26+ Clang
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -DFMT_CONSTEVAL=constexpr'
        end
      end
    end
  end
end
