require_relative '../ReactNativeModule/node_modules/react-native/scripts/react_native_pods'

node_modules_path = File.expand_path('../ReactNativeModule/node_modules', __dir__)
ENV['REACT_NATIVE_NODE_MODULES_DIR'] = node_modules_path

# Symlink node_modules into Expenso/ so Node can resolve react-native from here
local_node_modules = File.join(__dir__, 'node_modules')
unless File.exist?(local_node_modules)
  File.symlink('../ReactNativeModule/node_modules', local_node_modules)
end

platform :ios, '16.0'
prepare_react_native_project!

target 'Expenso' do
  use_react_native!(
    :path => '../ReactNativeModule/node_modules/react-native',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  pod 'RNReanimated', :path => '../ReactNativeModule/node_modules/react-native-reanimated'
  pod 'RNGestureHandler', :path => '../ReactNativeModule/node_modules/react-native-gesture-handler'
  pod 'RNSVG', :path => '../ReactNativeModule/node_modules/react-native-svg'

  post_install do |installer|
    react_native_post_install(
      installer,
      '../ReactNativeModule/node_modules/react-native',
      :mac_catalyst_enabled => false
    )

    # Workaround for fmt consteval errors with Xcode 26+ Clang
    # Patch the generated xcconfig files directly, since build settings
    # set on the Xcode target are overridden by xcconfig files.
    Dir.glob(File.join(installer.sandbox.root, 'Target Support Files', 'fmt', '*.xcconfig')).each do |xcconfig_path|
      content = File.read(xcconfig_path)
      unless content.include?('FMT_CONSTEVAL')
        content = content.gsub(
          /^OTHER_CPLUSPLUSFLAGS = (.*)$/,
          'OTHER_CPLUSPLUSFLAGS = \1 -DFMT_USE_CONSTEVAL=0 -DFMT_CONSTEVAL=constexpr'
        )
        # If no existing OTHER_CPLUSPLUSFLAGS, append it
        unless content.include?('OTHER_CPLUSPLUSFLAGS')
          content += "\nOTHER_CPLUSPLUSFLAGS = $(inherited) -DFMT_USE_CONSTEVAL=0 -DFMT_CONSTEVAL=constexpr\n"
        end
        File.write(xcconfig_path, content)
      end
    end
  end
end
